"NeoBundle Scripts-----------------------------
if has('vim_starting')
 if &compatible
   set nocompatible " Be iMproved
 endif

 " Required:
 set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('~/.vim/bundle'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" Add or remove your Bundles here:
" NeoBundle 'Shougo/neosnippet.vim'
" NeoBundle 'Shougo/neosnippet-snippets'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'ctrlpvim/ctrlp.vim'
NeoBundle 'flazz/vim-colorschemes'
NeoBundle 'bling/vim-airline'
NeoBundle 'tpope/vim-surround'
NeoBundle 'Lokaltog/vim-easymotion'
NeoBundle 'ervandew/supertab'
NeoBundle 'scrooloose/syntastic'

" Required:
call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck
"End NeoBundle Scripts-------------------------

" remove splash screen
set shortmess+=I

" turn on syntax highlighting
syntax enable

colorscheme monokai

" use automatic tab indentation
set shiftwidth=4
set tabstop=4
set softtabstop=4
set noexpandtab

" automatic indentation settings
filetype plugin indent on

" use unix line endings by default
set fileformats=unix,dos

" turn on incremental searching as you type
set incsearch
:
" status line
set laststatus=2 " Always display the status line
set noshowmode " Hide the default mode text

" vim-airline
let g:airline_theme='murmur'
let g:airline_powerline_fonts=1

" change leader key from \ to ,
let mapleader=','

" set key code delay to 10ms
" only wait a very short time for terminal key codes
" these aren't used by modern terminals
set ttimeoutlen=10
