-- require('avante').setup({
--   provider = 'copilot',
--   providers = {
--     copilot = {
--       model = 'claude-3.7-sonnet'
--     },
--   },
--   system_prompt = function()
--     local hub = require('mcphub').get_hub_instance()
--     return hub and hub:get_active_servers_prompt() or ''
--   end,
--   custom_tools = function()
--     return {
--       require('mcphub.extensions.avante').mcp_tool()
--     }
--   end,
-- })
--
-- -- Avante keymaps
-- vim.keymap.set({ "n", "v" }, "<Leader>aa", "<Cmd>AvanteAsk<CR>", { noremap = true, silent = true })
-- vim.keymap.set({ "n", "v" }, "<Leader>ae", "<Cmd>AvanteEdit<CR>", { noremap = true, silent = true })
-- vim.keymap.set({ "n", "v" }, "<Leader>af", "<Cmd>AvanteFocus<CR>", { noremap = true, silent = true })
-- vim.keymap.set({ "n", "v" }, "<Leader>as", "<Cmd>AvanteStop<CR>", { noremap = true, silent = true })
