-- sudo-tee/opencode.nvim
-- require('opencode').setup({
--   keymap = {
--     global = {
--       toggle = '<leader>aa', -- Open opencode. Close if opened
--       open_input = '<leader>ai', -- Opens and focuses on input window on insert mode
--       open_input_new_session = '<leader>aI', -- Opens and focuses on input window on insert mode. Creates a new session
--       open_output = '<leader>ao', -- Opens and focuses on output window
--       toggle_focus = '<leader>at', -- Toggle focus between opencode and last window
--       close = '<leader>aq', -- Close UI windows
--       select_session = '<leader>as', -- Select and load a opencode session
--       configure_provider = '<leader>ap', -- Quick provider and model switch from predefined list
--       diff_open = '<leader>ad', -- Opens a diff tab of a modified file since the last opencode prompt
--       diff_next = '<leader>a]', -- Navigate to next file diff
--       diff_prev = '<leader>a[', -- Navigate to previous file diff
--       diff_close = '<leader>ac', -- Close diff view tab and return to normal editing
--     }
--   }
-- })

---------------------------------------------
-- NickvanDyke/opencode.nvim
-- local oc = require('opencode')
--
-- vim.keymap.set({ 'n', 'v' }, '<leader>aa', function() oc.toggle() end)
-- vim.keymap.set({ 'n', 'v' }, '<leader>aq', function() oc.ask() end)
-- vim.keymap.set({ 'n', 'v' }, '<leader>aQ', function() oc.ask('@file') end)
-- vim.keymap.set({ 'n', 'v' }, '<leader>an', function() oc.command('/new') end)
-- vim.keymap.set({ 'n', 'v' }, '<leader>ae', function() oc.prompt('Explain @cursor and its context') end)
-- vim.keymap.set({ 'n', 'v' }, '<leader>ar', function() oc.prompt('Review @file for correctness and readability') end)
-- vim.keymap.set({ 'n', 'v' }, '<leader>af', function() oc.prompt('Fix these @diagnostics') end)
-- vim.keymap.set({ 'n', 'v' }, '<leader>ad', function() oc.prompt('Add documentation comments for @selection') end)
